apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mm1-gateway
  namespace: spe-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mm1-virtualservice
  namespace: spe-system
spec:
  hosts:
  - "*"
  gateways:
  - mm1-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: mm1-server
        port:
          number: 8080
    timeout: 300s  # Handle high service times
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mm1-destinationrule
  namespace: spe-system
spec:
  host: mm1-server
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30s
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 100
        maxRequestsPerConnection: 10
        maxRetries: 3
        h2UpgradePolicy: UPGRADE
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mm1-peer-auth
  namespace: spe-system
spec:
  selector:
    matchLabels:
      app: mm1-server
  mtls:
    mode: PERMISSIVE
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mm1-telemetry
  namespace: spe-system
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        cluster_name:
          value: "mm1_service"
        service_name:
          value: "mm1-server"